language: python
python:
- 2.7
install:
- pip install "blumpkin>=0.2,<0.3"
- pip install -e .[tests]
- python setup.py develop
script:
- nosetests -sv --with-xunitmp --with-cov --cov=thed --cov-report term-missing
- coverage combine
- coverage report
- coverage xml
- blumpkin coverage coverage.xml thed.api:90
after_success:
- find thed -name "*.py" | xargs pep8 --ignore=E711 | tee pep8.out
- blumpkin create-pypi
- blumpkin publish --on-tag
env:
  global:
  - PYPI_INDEX=""
  - PYPI_SERVER=""
  - PYPI_USERNAME=balanced-butler
  - secure: dkXPg5IeShMvbv78eiwtHWcBTcLuuvelFte2tsbJ/YbtbcW4xCc+r1AvVP/dVjEt0xLIMfYCKuSG6gTuvFljWU+mQBuwPrDTQrfpYde/FbkwFxkLhMJrhIdEoE8pSq22cAcUpSUNmHleT6oCYtR5O1ZBcv9DApHJu71cr7ra8t4=
